<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH5v2wlx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH5v2wlx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerH5v2wlx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerH5v2wlx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerH5v2wlx\appDevDebugProjectContainer(array(
    'container.build_hash' => 'H5v2wlx',
    'container.build_id' => '2ef18618',
    'container.build_time' => 1578835315,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerH5v2wlx');
